version: "3"
services:
    locationapi:
        build:
            context: ./Api/TestCase.Location.Api
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - mssqlserver
            - rabbitmq
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
 
    distancecalculationconsumer:
        build:
            context: ./Consumer/TestCase.DistanceCalculation.Consumer
            dockerfile: Dockerfile
        ports:
            - "8001:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        depends_on:
            - mssqlserver
            - rabbitmq

    mssqlserver:
        image: "mcr.microsoft.com/mssql/server"
        container_name: mssqlserver        
        environment:
            SA_PASSWORD: "B65k123456"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
        ports:
            - 5672:5672
            - 15672:15672